### ISSUE TITLE
As a developer, I need access to the user database to verify our FAS users

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#102]
**Acceptance Criteria:**

Log ticket on infra tracker (s) to gain access
Add link of open ticket to this user story

**Definition of done**

Gained access to database to verify users and test script and carry out other tasks noted on user story? 

Note : Broken down within a larger user story https://github.com/fedora-infra/securitas/issues/55

**Comment by abompard** [comment]
This is technically simple but will probably require some discussions to happen because we're dealing with very sensitive data and we want to do that securely.

**Comment by relrod** [comment]
FWIW, fas2ipa will work just fine if you run it against FAS as a normal user without `accounts` access. You just won't be able to import everything about accounts that have privacy set.

So this isn't really a blocker.

**Comment by puiterwijk** [comment]
I am very concerned about this.
We should not use data from production deployments in development environments, since that will at some point go out of sync, and any copies any of us make and accidentally check into git or anything still fall under privacy regulations.

Instead, there should be some mock data and people should use that.

**Comment by abompard** [comment]
If I remember correctly, we only found out about accounts that don't import well because the script failed when it was run against that data, not because we anticipated the variations that can be in the prod database. I don't think we need a dump of the database, more like credentials that would be able to access the data that we need to migrate, to make sure we handle the corner cases.
If we can't have privileged access (even temporarily) for that, it's totally understandable and we'll test against the data we can have with regular accesses (and hope outliers didn't have privacy set ;-) )

**Comment by StephenCoady** [comment]
> If I remember correctly, we only found out about accounts that don't import well because the script failed when it was run against that data, not because we anticipated the variations that can be in the prod database.

Do we now know what those variations are?

> If we can't have privileged access (even temporarily) for that, it's totally understandable and we'll test against the data we can have with regular accesses (and hope outliers didn't have privacy set ;-) )

So does this paired with my above question mean we may not need to complete this user story at all?

**Comment by abompard** [comment]
> > If I remember correctly, we only found out about accounts that don't import well because the script failed when it was run against that data, not because we anticipated the variations that can be in the prod database.
> 
> Do we now know what those variations are?

Yeah, I'm thinking of users who have only one "word" in their name field, and IPA wants a first name and a last name, there's also users who don't have a name at all. My point is that it's hard to anticipate the diversity of the production data and prepare for it without access to prod data.

We can also allocate more time to fixing those errors when we run into them while migrating, but it seems more risky because it's hard to know how long it'll take at that point, and it'll probably waste other people's time (because deployment has to be more coordinated with ops than dev). I don't know which is the lesser of the two evils.

**Comment by StephenCoady** [comment]
Ah sorry, I thought you meant the variations between actual production data and publicly accessible data. I didn't realise the that stuff only popped up when we got some prod data.

**Comment by abompard** [comment]
Alright, it's too risky to give devs access to prod data for security and privacy reasons.
