### ISSUE TITLE
Setup and Configure an Ipsilon instance that uses a FreeIPA backend

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#16]

**Comment by abompard** [comment]
Is this for development? If so, it would indeed be useful to have an Ipsilon instance in Communishift alongside other apps so we can test integration.
In production, we should reconfigure the existing one.
In staging, we don't want to reconfigure the existing one just yet because it may break authentication for the staging env. But we can do it when prod is updated.
