### ISSUE TITLE
Consider adding 'blog' pref

### ISSUE THREAD

**Issue by nirik** [fedora-infra/noggin#188]
Might be nice to have a blog pref and have it assume https:// (since we don't want to use http in this day and age)

**Comment by pypingou** [comment]
Just to add we likely want to support multiple blogs per person.

The fields needed will be:
- blog URL
- blog name?
- RSS feed url
- face like we have now in the ``.planet`` file?

**Comment by nirik** [comment]
I think blog url / name and rss feed can all be gotten from the rss feed? Although I suppose they might filter the rss part to 'tag=fedora' or something so you might want to know the unfiltered blog url. Name should be gettable via rss. 

face would be nice... or we could just use gravatar?

**Comment by abompard** [comment]
This is starting to look more like a database and not a directory... For example if we have 4 multi-valued fields as described in Pingou's comment, it will not be easy to match which URL corresponds to which RSS feed URL, since LDAP does not retain order of the multi-valued attributes.

Maybe just the blog URL, and something could propose a .planet file based on that ? (the RSS url can be found in the blog's `<head>` usually). I don't think we can replace it entirely.
