### ISSUE TITLE
Identify what they are using that dummy user for

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#24]

**Comment by abompard** [comment]
If you mean the `fedoradummy` account in FAS, I've seet it used in ansible for the following apps:
- datanommer
- supybot
- ambassadors map (membership-maps)
- zanata

I *think* they use it to make user queries to FAS. I'm not sure what this User Story implies, should we create the equivalent account in IPA? Is it useless because accounts can now be queried anonymously?

**Comment by abompard** [comment]
Ryan and I are building a list of applications that use the dummy FAS user here: https://github.com/fedora-infra/fasjson/wiki. Please re-open if I haven't understood what this issue was about.
