### ISSUE TITLE
As a registered community member, I want to be able to indicate my Matrix IDs in my account

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-infra/noggin#248]
In the same vein that we have for IRC nicks, there's a need to be able to indicate Matrix IDs (MXIDs).

Per [the Matrix specification](https://matrix.org/docs/spec/#users), the handle format is `@user:server`. The [full specification of the identifier format](https://matrix.org/docs/spec/appendices#identifier-grammar) should probably be implemented to validate whether an entered MXID is valid or not and to support the proper uniqueness constraints.

This is a requirement for openSUSE, as we're going to be standing up a Matrix server and "rehome" all community channels on it. Consequently, primacy will be moving from IRC to the Matrix, and we need a way to map member presence in the Matrix to accounts in the same way Fedora does with IRC.

This will also be useful for Fedora, as Matrix-only rooms for Fedora are starting to exist, and having the mapping would be very useful there, too.

**Comment by Conan-Kudo** [comment]
openSUSE has completed the setup of its new Matrix server, though we do not yet allow users to sign into the system yet. But as the Matrix server has federation turned on, the Matrix rooms (that map to IRC channels) are accessible by users from other Matrix servers.

**Comment by Conan-Kudo** [comment]
This is now important for Fedora, as there are ongoing discussions right now on transitioning real-time chat primacy from IRC to Matrix in Fedora. For reference, here are some of the discussions:

* Council discussion thread on switching to Matrix [on the forums](https://discussion.fedoraproject.org/t/the-future-of-real-time-chat-discussion-for-the-fedora-council/24628)
* Discussion on [development mailing list](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/T7C25NUEKEB3GLA2GO752XISR6HHFJR7/)
* Fedora Council ticket: [pagureio#Fedora-Council/tickets#342](https://pagure.io/Fedora-Council/tickets/issue/342)

@mattdm posted an [update to the development mailing list](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/52Y3STF567JJ7KU4DT76X4NJGYGUMIX7/) indicating that we're going forward with implementing this transition imminently.

It'd be great to have movement on this so that we can have this in the same way we have IRC nicks with the new AAA system.

**Comment by mattdm** [comment]
Note that everyone will have a primary "fasid@fedora.im" (or "fasid@fedoraproject.org") matrix ID. This would be to indicate additional addresses (like whatever@matrix.org) and possibly to indicate a preferred one.

**Comment by Conan-Kudo** [comment]
Indeed. As a concrete example, I would have `@ngompa:fedoraproject.org` (or `@ngompa:fedora.im`) MXID. But I also have `@conan_kudo:matrix.org` and currently primarily use that. This would make it easy for Fedora bots to know who to respond to, and for other people to easily figure out how to reach me.

**Comment by mscherer** [comment]
I would propose that adding the Fedora MXID should be at least tied to successful use by the user, not displayed by default. 

Otherwise, you can't really know if contacting someone over matrix is going to work, unlike the email alias. And so, if people start to assume someone will get their message when this is not the case, the sender will end frustrated, and start to see the system as unreliable, and that's not great.

**Comment by mscherer** [comment]
In fact, shouldn't this be generalized to more messaging systems (eg, telegram, xmpp, etc) ?

**Comment by michel-slm** [comment]
> I would propose that adding the Fedora MXID should be at least tied to successful use by the user, not displayed by default.

I agree, but as for generalizing this, it should be applied to both emails and IRC too. Until we can do that I don't think requiring it for Matrix only makes sense.

**Comment by mscherer** [comment]
For email, we know the alias would work since there is a working email as a per condition for opening a FAS account to which is it forwarded (and we can display on FAS+1 only), so it make sense to display once we know it is activated, since people will receive email there (minus technical issues). Now, maybe this is isn't the case now, and if it isn't, then I think it should be.

For IRC/XMPP/others, it has to be added manually, so that would be a strong signal it is being used and valid.
