### ISSUE TITLE
[secaudit-blocking] Outdated dependencies

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/noggin#338]
Part of secaudit #316, blocking.

The dependencies in `pyproject.toml` and `poetry.lock` are outdated.
This is a violation of the `Dependencies` section of the [Fedora Infrastructure Application Security Policy](https://docs.pagure.org/infra-docs/dev-guide/security_policy.html#dependencies).

Additionally, it seems dependabot is in use, but its PRs do not seem to be merged in an automated fashion, which means that they may be lagging for a while, like #324, which is idle for 7 days by now.
Additionally, it seems that it doesn't propose updates for many things, like for example `idna` or `certifi`.

Running `poetry update --dry-run` after setting all version requirements to `"*"` results in the following proposed changes:
```
  - Updating idna (2.9 -> 2.10)
  - Updating six (1.14.0 -> 1.15.0)
  - Updating cffi (1.14.0 -> 1.14.1)
  - Updating hyperlink (19.0.0 -> 20.0.1)
  - Updating cryptography (2.9.2 -> 3.0)
  - Updating multidict (4.7.5 -> 4.7.6)
  - Updating smmap (3.0.2 -> 3.0.4)
  - Updating certifi (2020.4.5.1 -> 2020.6.20)
  - Updating gitdb (4.0.4 -> 4.0.5)
  - Updating more-itertools (8.2.0 -> 8.4.0)
  - Updating packaging (20.3 -> 20.4)
  - Updating py (1.8.1 -> 1.9.0)
  - Updating pytz (2019.3 -> 2020.1)
  - Updating toml (0.10.0 -> 0.10.1)
  - Updating urllib3 (1.25.9 -> 1.25.10)
  - Updating wcwidth (0.1.9 -> 0.2.5)
  - Updating yarl (1.4.2 -> 1.5.1)
  - Updating appdirs (1.4.3 -> 1.4.4)
  - Updating coverage (5.1 -> 5.2.1)
  - Updating fedora-messaging (2.0.1 -> 2.0.2)
  - Updating gitpython (3.1.1 -> 3.1.7)
  - Updating regex (2020.4.4 -> 2020.7.14)
  - Updating requests (2.23.0 -> 2.24.0)
  - Updating semantic-version (2.8.4 -> 2.8.5)
  - Updating soupsieve (1.9.5 -> 1.9.6)
  - Updating stevedore (1.32.0 -> 3.2.0)
  - Updating wtforms (2.2.1 -> 2.3.3)
  - Updating isort (5.2.2 -> 5.3.2)
  - Updating sphinx (3.1.2 -> 3.2.0)
  - Updating whitenoise (5.1.0 -> 5.2.0)
```

**Comment by abompard** [comment]
> Additionally, it seems dependabot is in use, but its PRs do not seem to be merged in an automated fashion, which means that they may be lagging for a while, like #324, which is idle for 7 days by now.

I'm going to configure Dependabot to merge pull requests. At the moment it's a bit risky since CI is broken but it should be safe to automatically merge pull requests that pass CI.

> Additionally, it seems that it doesn't propose updates for many things, like for example idna or certifi

Dependabot is configured to only propose updates for direct dependencies, not sub-dependencies. I can configure it to propose updates for indirect dependencies too.

Some of those listed dependencies are however unsafe to merge automatically, since they update their major version number, and according to semver this means at least one backwards-incompatible change (see the `stevedore` update for example). These should be manually reviewed.
There are, however, dependencies that obviously don't follow semver, such as certifi and pytz. I'll configure an exception for those.

However, I don't think we should update the `pyproject.toml` file with newer versions automatically, only the `poetry.lock` file. If we automatically update minimum version to the latest available, it will make things harder for downstream packagers who build RPMs with what the distribution has available at some point in time (such as EL8). Poetry will convert a `pyproject.toml` requirement such as `requests = "^2.22.0"` to `requests>=2.22.0,<3.0.0` in the published tarball, and it seems like the best way to allow packagers to use any compatible version. It does however rely on the dependency's upstream project to release security patches for older release branches, or on packagers to backport them, but it seems like a reasonable requirement.

Would that work from a security point of view?

**Comment by abompard** [comment]
Hmm I don't seem to be able to configure dependabot to update `certifi` and `pytz` regardless of the major version number change. That's a bit too bad, I'm not sure we'll remember to update the lock file manually for those.
