### ISSUE TITLE
As a complete newcomer to Fedora or CentOS, I want to be able to register so that I can contribute to the project in some way.

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#52]

**Comment by sanjayankur31** [comment]
FAS also provides access to our user forums/mailing lists such as [Ask Fedora](https://ask.fedoraproject.org/), so it isn't limited to contributors only.  To reflect this, should we tweak the user story to something on the lines of:  "As a complete newcomer ..., I want to be able to register so that I can access community resources"?

**Comment by abompard** [comment]
That's already done.
