### ISSUE TITLE
Improve lost password / token page

### ISSUE THREAD

**Issue by nirik** [fedora-infra/noggin#678]
The lost password page has a section for OTP: 

"Did you lose your OTP token?

If you have lost your OTP token you need to send an email to admin@fedoraproject.org . Please sign this email using the GPG key associated with your account if possible, so that the administrator can verify your identity."

Where 'admin@fedoraproject.org' is a mailto link to: 

mailto:admin@fedoraproject.org?Subject=Lost OTP

This is sadly resulting in us getting a bunch of emails that are Subject "Lost OTP" with no body. I am not sure if people are clicking on it because they want to reset their password, because they are confused, or because they are bots, but it sucks up a lot of time answering them all. :( 

So, perhaps we could replace that mailto link with a 'admin at fedoraproject.org' ? Or just 'admin@fedoraproject.org' thats not a mailto link? Or perhaps we could split the lost otp off to a new page? Also, perhaps that should be "Did you loose your LAST OTP token?' since if you have others you can use them. Or perhaps we should just point it to a doc/wiki page that we can edit and adjust more easily? Or a template config?

Open to ideas on how best to solve it... :)

**Comment by nirik** [comment]
Oh, I wonder... can we authenticate someone by password only before allowing them to request a OTP reset and make that a form that mails admin?

**Comment by abompard** [comment]
In the interest of time I'm going to fix this issue now. I replaced the paragraph with:

----

**Did you lose your last OTP token?**

If you have lost your last OTP token you need to send an email to [admin at fedoraproject.org](mailto:admin%20at%20fedoraproject.org?subject=Lost%20OTP). Please sign this email using the GPG key associated with your account if possible, so that the administrator can verify your identity.

If you had multiple tokens and lost one, you can use another to login and delete the lost token from your account.

----

What do you think?

**Comment by nirik** [comment]
IMHO we should drop the mailto: entirely... users can easily type the address in, but whats happening now is that bots just scan the pages and find the mailto link and send messages to it. ;( 

Also, perhaps we could add a "If you haven't enrolled a otp token, you don't have one and this doesn't apply to you" ? We seem to get people who think it's something that they just forgot when they never had one to begin with. :)

**Comment by abompard** [comment]
Done. Here's how it looks like in my PR:
![Capture d’écran de 2021-10-01 10-19-33](https://user-images.githubusercontent.com/95780/135588504-8aac810d-7055-4e59-9aff-8f6bb7a7de1d.png)

(The email is not a link)

**Comment by nirik** [comment]
Looks great to me!
